/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

var common = require("./common");

module.exports = {
    solveProblem: function () {
        console.log("Problem 2.  Fibonacci");

        var previousTerm = 0;
        var currentTerm = 1;
        var sum = 0;

        for (var i = 0; i < 100; i++) {
            var nextTerm = previousTerm + currentTerm;

            if (nextTerm > 4000000) break;

            if (common.isEven(nextTerm)) {
                sum += nextTerm;
            }

            previousTerm = currentTerm;
            currentTerm = nextTerm;
        }

        console.log(`Final Term := ${currentTerm}`);

        console.log(`Sum of Even Terms is ${sum}`);
    }
}.solveProblem();

