/*
     Problem from Site

     The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:

    1: 1
    3: 1,3
    6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over five hundred divisors?

*/

var common = require("./common");
var colors = require('colors/safe');

function findTriangles(number = 500000) {

    var triangles = [];
    var lastValue = 0;

    for (i = 1; i < number + 1; i++) {
        var currentValue = i + lastValue;

        triangles.push(currentValue);

        lastValue = currentValue;
    }

    return triangles;

}

function getPrimeExpontentCount(array) {
    var tracker = [];

    function getFromTracker(number) {

        var foundIdex = -1;

        tracker.forEach((element, index) => {
            if (element.number == number) foundIdex = index;
        });

        return foundIdex;
    }

    for (var i = 0; i < array.length; i++) {
        var current = array[i];

        var foundIndex = getFromTracker(current);

        if (foundIndex != -1) {
            tracker[foundIndex].count++;
        } else {
            tracker.push({
                count: 1,
                number: current
            });
        }
    }

    var exponents = [];

    tracker.forEach(element => {
        exponents.push(element.count);
    });

    return exponents;
}

module.exports = {
    solveProblem: async function () {

        // console.log('Finding Triangles');

        // var triangles = findTriangles();

        // console.log('Done finding Triangles');
        // console.log('Looking for 500 factors.');

        var number = 15802;

        var primeFactors = common.getPrimeFactors(number);

        console.log(`PrimeFactors ${primeFactors}`);

        var occurances = getPrimeExpontentCount(primeFactors);

        for (var i = 0; i < occurances.length; i++) {
            occurances[i]++;
        }

        var factors = common.getFactors(number);

        console.log(`For ${primeFactors} has occurances ${occurances} and has ${common.productOfArray(occurances)} factors form common ${factors.length}`);

        // for (var i = 100000; i < triangles.length; i++) {
        //     var current = triangles[i];

        //     var factors = common.getFactors(current);

        //     //console.log(`Triangle ${current} has ${factors.length} factors`);

        //     if (factors.length == 499) {
        //         console.log(`Triangle ${current} has ${factors.length} factors`);

        //         console.log("Exiting . . .");

        //         return;
        //     }
        // }
    }
}